### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [3]:
vector = np.random.uniform(0, 1, 10)
print(vector, vector.shape)

matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
print(matrix, matrix.shape)

[0.09897069 0.49064241 0.65731879 0.95742322 0.76114444 0.68634941
 0.81874758 0.81098225 0.88996731 0.18246443] (10,)
[[11 14 17]
 [20 23 26]
 [29 32 35]] (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [4]:
vector = np.round(vector + 10, 2)
print(vector)

[10.1  10.49 10.66 10.96 10.76 10.69 10.82 10.81 10.89 10.18]


In [5]:
matrix = matrix * 2
print(matrix)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [6]:
vector_squared = np.square(vector)
print(vector_squared)

[102.01   110.0401 113.6356 120.1216 115.7776 114.2761 117.0724 116.8561
 118.5921 103.6324]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [7]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [8]:
result_matrix = np.dot(B, A)
print(result_matrix, result_matrix.shape)

[[0.7281 0.5202]
 [0.2034 0.2846]] (2, 2)


In [9]:
result_vector = np.dot(result_matrix, C)
print(result_vector, result_vector.shape)

array([[0.5202],
       [0.2846]])

In [10]:
result_matrix_2 = np.dot(result_matrix, D)
print(result_matrix_2, result_matrix_2.shape)

[[0.5202 0.7281]
 [0.2846 0.2034]] (2, 2)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [11]:
matrix = result_matrix.T
print(matrix, matrix.shape)

[[0.7281 0.2034]
 [0.5202 0.2846]] (2, 2)


In [13]:
vector = vector.T
print(vector, vector.shape)

[10.1  10.49 10.66 10.96 10.76 10.69 10.82 10.81 10.89 10.18] (10,)


In [14]:
column_vector = np.expand_dims(vector, axis=1)
print(column_vector, column_vector.shape)

[[10.1 ]
 [10.49]
 [10.66]
 [10.96]
 [10.76]
 [10.69]
 [10.82]
 [10.81]
 [10.89]
 [10.18]] (10, 1)


In [16]:
vector = column_vector.T
print(vector, vector.shape)

[[10.1  10.49 10.66 10.96 10.76 10.69 10.82 10.81 10.89 10.18]] (1, 10)
